### Save a new URL
POST {{host}}/url
Content-Type: application/json
API_KEY: abc123

{
    "url": "https://www.google.com"
}


### Get URL by ID
GET {{host}}/ac6bb669

### Get URL unwraped
GET {{host}}/ac6bb669/unwrap

